### ISSUE TITLE
Bug Report Nina Krugger Damage Animation

### ISSUE THREAD

**Issue by kokizzu** [questforboobs/gkdata#1]
Hi, just want to report that Nina Krugger's damage animation is a bit skewed..

http://gkgirls.info.gf/spine.php?id=c_010&skin=1

btw, awesome work doing all this :3

**Comment by questforboobs** [comment]
The various animation issues are because the converter used to take the .skel files from the game and turn them into JSON is not 100% complete. Bugs about it are better reported at its own repo: https://github.com/questforboobs/skel2json
